/* =============================================================================
 * Key
 * 
 * enum class containing keyboard key codes.
 * ===========================================================================*/
#pragma once
#include <SDL2/SDL_keycode.h>

namespace SDG
{
    enum class Key : SDL_Keycode
    {
        A = SDLK_a,
        B = SDLK_b,
        C = SDLK_c,
        D = SDLK_d,
        E = SDLK_e,
        F = SDLK_f,
        G = SDLK_g,
        H = SDLK_h,
        I = SDLK_i,
        J = SDLK_j,
        K = SDLK_k,
        L = SDLK_l,
        M = SDLK_m,
        N = SDLK_n,
        O = SDLK_o,
        P = SDLK_p,
        Q = SDLK_q,
        R = SDLK_r,
        S = SDLK_s,
        T = SDLK_t,
        U = SDLK_u,
        V = SDLK_v,
        W = SDLK_w,
        X = SDLK_x,
        Y = SDLK_y,
        Z = SDLK_z,
        Zero = SDLK_0,
        One = SDLK_1,
        Two = SDLK_2,
        Three = SDLK_3,
        Four = SDLK_4,
        Five = SDLK_5,
        Six = SDLK_6,
        Seven = SDLK_7,
        Eight = SDLK_8,
        Nine = SDLK_9,
        Tab = SDLK_TAB,
        CapsLock = SDLK_CAPSLOCK,
        LShift = SDLK_LSHIFT,
        RShift = SDLK_RSHIFT,
        LControl = SDLK_LCTRL,
        RControl = SDLK_RCTRL,
        LAlt = SDLK_LALT,
        RAlt = SDLK_RALT,
        Space = SDLK_SPACE,
        Insert = SDLK_INSERT,
        Delete = SDLK_DELETE,
        Backspace = SDLK_BACKSPACE,
        Slash = SDLK_SLASH,
        BackSlash = SDLK_BACKSLASH,
        Quote = SDLK_QUOTE,
        BackQuote = SDLK_BACKQUOTE,
        Colon = SDLK_COLON,
        Comma = SDLK_COMMA,
        Period = SDLK_PERIOD,
        Home = SDLK_HOME,
        PageUp = SDLK_PAGEUP,
        PageDown = SDLK_PAGEDOWN,
        End = SDLK_END,
        Left = SDLK_LEFT,
        Right = SDLK_RIGHT,
        Up = SDLK_UP,
        Down = SDLK_DOWN,
        RBracket = SDLK_RIGHTBRACKET,
        LBracket = SDLK_LEFTBRACKET,
        Equals = SDLK_EQUALS,
        PrintScreen = SDLK_PRINTSCREEN,
        Dash = SDLK_MINUS,
        Minus = SDLK_MINUS,
        F1 = SDLK_F1,
        F2 = SDLK_F2,
        F3 = SDLK_F3,
        F4 = SDLK_F4,
        F5 = SDLK_F5,
        F6 = SDLK_F6,
        F7 = SDLK_F7,
        F8 = SDLK_F8,
        F9 = SDLK_F9,
        F10 = SDLK_F10,
        F11 = SDLK_F11,
        F12 = SDLK_F12,
        F13 = SDLK_F13,
        F14 = SDLK_F14,
        F15 = SDLK_F15,
        F16 = SDLK_F16,
        F17 = SDLK_F17,
        F18 = SDLK_F18,
        F19 = SDLK_F19,
        F20 = SDLK_F20,
        F21 = SDLK_F21,
        F22 = SDLK_F22,
        F23 = SDLK_F23,
        F24 = SDLK_F24,
        Escape = SDLK_ESCAPE,
    };
}